# -*- coding: utf-8 -*-
"""
Испанский канал: арабский для испаноговорящих.
Содержание уроков и испанские формулировки; механика — в shorts_core.

    python shorts_es.py 1 2 3

Голоса: ведущая — бесплатная es-MX-DaliaNeural (латиноамериканский
испанский — самая большая аудитория), арабские слова — носитель
ar-SA-ZariyahNeural.

Серия-крючок здесь сильнее английской: в испанском около четырёх тысяч
слов арабского происхождения (azúcar, aceite, ojalá, naranja, almohada),
и почти каждое — готовый ролик «ya hablas árabe».
"""

import shorts_core as core

# hook — крючок сверху, ar — арабское слово, translit — «слово — перевод»
# (слово до тире озвучивает носитель), teach — обучающая фраза,
# cta — призыв, themes — поиск фото на Wikimedia (только на английском).
# Слово из translit должно дословно встречаться в teach.
LESSONS = {
    1:  dict(hook="Hola en árabe", ar="مَرْحَبًا", translit="Marhaba — hola",
             teach="La forma más fácil de saludar en árabe es Marhaba. Dilo con una sonrisa: ¡Marhaba!",
             cta="¡Suscríbete y aprende una palabra al día!",
             themes=["sheikh zayed mosque", "sahara dunes", "arabic calligraphy"]),
    2:  dict(hook="Ya hablas árabe: azúcar", ar="سُكَّر", translit="Sukkar — azúcar",
             teach="La palabra azúcar viene del árabe Sukkar. Sukkar, azúcar. ¿Te suena parecido?",
             cta="¡Suscríbete, hay muchas más palabras así!",
             themes=["sugar cane field", "sugar cubes", "baklava"]),
    3:  dict(hook="Cómo decir gracias", ar="شُكْرًا", translit="Shukran — gracias",
             teach="Gracias en árabe es Shukran. Úsalo en todas partes: ¡Shukran!",
             cta="¡Suscríbete, mañana más frases!",
             themes=["arabic coffee", "sahara dunes", "sheikh zayed mosque"]),
    4:  dict(hook="Ojalá es una palabra árabe", ar="إِنْ شَاءَ اللّٰه",
             translit="In sha Allah — si Dios quiere",
             teach="Cuando dices ojalá, hablas árabe: viene de In sha Allah, que significa si Dios quiere.",
             cta="¡Suscríbete y descubre más sorpresas!",
             themes=["sunrise desert", "sheikh zayed mosque", "arabic calligraphy"]),
    5:  dict(hook="El saludo de dos mil millones", ar="السَّلَامُ عَلَيْكُمْ",
             translit="As-salamu alaykum — la paz sea contigo",
             teach="De Marruecos a Indonesia la gente se saluda con As-salamu alaykum. Significa la paz sea contigo.",
             cta="¡Suscríbete y aprende árabe con nosotros!",
             themes=["sheikh zayed mosque", "mosque interior", "arabic calligraphy"]),
    6:  dict(hook="Sí y no en árabe", ar="نَعَمْ / لَا", translit="Na'am / La — sí / no",
             teach="Las dos palabras más útiles que vas a aprender. Sí y no en árabe: Na'am / La.",
             cta="¡Suscríbete, esto se pone mejor!",
             themes=["morocco desert", "desert sunset", "sheikh zayed mosque"]),
    7:  dict(hook="Aceite viene del árabe", ar="الزَّيْت", translit="Az-zayt — el aceite",
             teach="Aceite viene del árabe Az-zayt. Por eso decimos aceituna y aceitera.",
             cta="¡Dale like si te gusta el aceite de oliva!",
             themes=["olive oil", "olive grove", "olives"]),
    8:  dict(hook="Cómo preguntar dónde", ar="أَيْنَ", translit="Ayna — dónde",
             teach="¿Perdido en la medina? Solo pregunta Ayna. Ayna significa dónde.",
             cta="¡Guárdalo para tu próximo viaje!",
             themes=["medina morocco", "old map", "sahara dunes"]),
    9:  dict(hook="¿Qué es esto?", ar="مَا هَذَا؟", translit="Ma hadha — qué es esto",
             teach="Señala cualquier cosa y pregunta: Ma hadha. Significa qué es esto.",
             cta="¡Suscríbete, el árabe es fácil!",
             themes=["moroccan lanterns", "dates fruit", "ceramic tiles"]),
    10: dict(hook="El cero es árabe", ar="صِفْر", translit="Sifr — cero",
             teach="El cero llegó a Europa a través del árabe: Sifr. De ahí viene cero y también cifra.",
             cta="¡Compártelo con alguien que ame las matemáticas!",
             themes=["arabic manuscript", "old books", "astrolabe"]),
    11: dict(hook="¿Cuánto cuesta?", ar="بِكَمْ؟", translit="Bikam — cuánto cuesta",
             teach="La pregunta más importante en cualquier mercado: Bikam. ¿Cuánto cuesta?",
             cta="¡Guárdalo antes de ir de compras!",
             themes=["morocco spices", "gold jewellery", "brass teapot"]),
    12: dict(hook="La palabra mágica Tayyib", ar="طَيِّب", translit="Tayyib — bien",
             teach="Tayyib significa bien, vale, de acuerdo. Los árabes lo dicen todo el tiempo: Tayyib.",
             cta="¡Suscríbete para tu árabe diario!",
             themes=["oasis palm", "palm trees sunset", "sahara dunes"]),
    13: dict(hook="¡Álgebra es árabe!", ar="الْجَبْر", translit="Al-jabr — álgebra",
             teach="El álgebra lleva el nombre de un libro árabe de Bagdad. En su título estaba la palabra Al-jabr, que significa restaurar.",
             cta="¡Etiqueta a quien odiaba el álgebra!",
             themes=["arabic manuscript", "astrolabe", "old books"]),
    14: dict(hook="¿Cómo te llamas?", ar="مَا اسْمُكَ؟", translit="Ma ismuk — cómo te llamas",
             teach="¿Conociste a alguien? Pregunta: Ma ismuk. ¿Cómo te llamas?",
             cta="¡Escribe tu nombre en los comentarios!",
             themes=["arabic calligraphy", "moroccan lanterns", "sheikh zayed mosque"]),
    15: dict(hook="Me llamo...", ar="اسْمِي", translit="Ismi — me llamo",
             teach="Para presentarte di Ismi y tu nombre. Ismi Maryam: me llamo Maryam.",
             cta="¡Preséntate en árabe aquí abajo!",
             themes=["arabic calligraphy", "medina morocco", "desert sunset"]),
    16: dict(hook="Naranja viene del árabe", ar="نَارَنْج", translit="Naranj — naranja",
             teach="La naranja llegó a España con su nombre árabe: Naranj. Naranj, naranja.",
             cta="¡Dale like si no lo sabías!",
             themes=["orange fruit", "orange tree", "citrus fruit"]),
    17: dict(hook="No entiendo", ar="لَا أَفْهَم", translit="La afham — no entiendo",
             teach="Toda persona que empieza necesita esta frase: La afham. No entiendo.",
             cta="¡Guárdala, te va a salvar!",
             themes=["old books", "arabic manuscript", "library"]),
    18: dict(hook="Buenos días en árabe", ar="صَبَاحُ الْخَيْر",
             translit="Sabah al-khayr — buenos días",
             teach="Buenos días se dice Sabah al-khayr. La respuesta es aún más bonita: mañana de luz.",
             cta="¡Suscríbete y empieza el día en árabe!",
             themes=["sunrise desert", "sunrise mosque", "sunrise"]),
    19: dict(hook="Almohada es árabe", ar="الْمِخَدَّة", translit="Al-mikhadda — la almohada",
             teach="Almohada viene del árabe Al-mikhadda. Piénsalo esta noche al dormir.",
             cta="¡Suscríbete, hay más palabras escondidas!",
             themes=["pillow", "bedroom interior", "cotton"]),
    20: dict(hook="Buenas tardes en árabe", ar="مَسَاءُ الْخَيْر",
             translit="Masa al-khayr — buenas tardes",
             teach="Cuando cae el sol se dice Masa al-khayr. Buenas tardes.",
             cta="¡Suscríbete para más saludos!",
             themes=["sunset mosque", "city lights evening", "desert sunset"]),
    21: dict(hook="Buenas noches en árabe", ar="تُصْبِحْ عَلَى خَيْر",
             translit="Tusbih ala khayr — buenas noches",
             teach="Buenas noches es Tusbih ala khayr. Literalmente: que amanezcas bien.",
             cta="¡Guárdalo y deséalo a alguien!",
             themes=["full moon", "night sky stars", "city night"]),
    22: dict(hook="Alfombra viene del árabe", ar="الْحَنْبَل", translit="Al-hanbal — la alfombra",
             teach="La alfombra tiene nombre árabe: Al-hanbal. Los tejidos llegaron con sus palabras.",
             cta="¡Dale like si te gustan las alfombras árabes!",
             themes=["persian carpet", "moroccan carpet", "textile pattern"]),
    23: dict(hook="¡Bienvenido en árabe!", ar="أَهْلًا وَسَهْلًا",
             translit="Ahlan wa sahlan — bienvenido",
             teach="La famosa hospitalidad árabe empieza con Ahlan wa sahlan. ¡Bienvenido!",
             cta="¡Bienvenido al canal, suscríbete!",
             themes=["moroccan door", "arabic door", "riad morocco"]),
    24: dict(hook="Adiós en árabe", ar="مَعَ السَّلَامَة",
             translit="Ma'a as-salama — adiós",
             teach="Despídete bonito: Ma'a as-salama. Vete con paz.",
             cta="¡Suscríbete, esto no es un adiós!",
             themes=["camel caravan", "desert sunset", "sunset"]),
    25: dict(hook="Arroz es palabra árabe", ar="الرُّزّ", translit="Ar-ruzz — el arroz",
             teach="El arroz llegó a España con su nombre árabe: Ar-ruzz. Ar-ruzz, arroz.",
             cta="¡Suscríbete para más historias de palabras!",
             themes=["rice field", "rice grains", "paella"]),
    26: dict(hook="¡Un momento!", ar="لَحْظَة", translit="Lahza — un momento",
             teach="Lahza significa un momento, un segundito. Lo vas a oír todo el tiempo: Lahza.",
             cta="¡Suscríbete, no pierdas ni un momento!",
             themes=["hourglass", "sand dunes wind", "sahara dunes"]),
    27: dict(hook="¡Estoy aprendiendo árabe!", ar="أَنَا أَتَعَلَّمُ الْعَرَبِيَّة",
             translit="Ana ata'allam al-arabiyya — estoy aprendiendo árabe",
             teach="Dilo con orgullo: Ana ata'allam al-arabiyya. ¡Estoy aprendiendo árabe!",
             cta="¡Suscríbete y aprendamos juntos!",
             themes=["arabic manuscript", "arabic calligraphy", "sahara dunes"]),
    28: dict(hook="Palabra del día: agua", ar="مَاء", translit="Maa — agua",
             teach="Sin agua no hay vida. Agua en árabe es Maa.",
             cta="¡Dale like si ya bebiste agua hoy!",
             themes=["water drops", "ocean waves", "waterfall"]),
    29: dict(hook="Palabra del día: pan", ar="خُبْز", translit="Khubz — pan",
             teach="El pan recién hecho es Khubz. Dilo: Khubz.",
             cta="¡Suscríbete antes de que te dé hambre!",
             themes=["bread baking", "wheat field"]),
    30: dict(hook="Palabra del día: casa", ar="بَيْت", translit="Bayt — casa",
             teach="Hogar, dulce hogar. Casa en árabe es Bayt.",
             cta="¡Guarda esta palabra!",
             themes=["old city street", "cozy house"]),
    31: dict(hook="Palabra del día: sol", ar="شَمْس", translit="Shams — sol",
             teach="El sol brilla para todos. Sol en árabe es Shams.",
             cta="¡Dale like si amas el sol!",
             themes=["sunrise timelapse", "sun clouds"]),
    32: dict(hook="Palabra del día: luna", ar="قَمَر", translit="Qamar — luna",
             teach="En la poesía árabe la luna significa belleza. Luna es Qamar.",
             cta="¡Suscríbete, mañana más palabras!",
             themes=["full moon", "night sky timelapse"]),
    33: dict(hook="Palabra del día: ciudad", ar="مَدِينَة", translit="Madina — ciudad",
             teach="Ciudad en árabe es Madina. De ahí viene el nombre de la medina, el casco antiguo.",
             cta="¡Suscríbete al canal!",
             themes=["city skyline night", "old arab city"]),
    34: dict(hook="Palabra del día: coche", ar="سَيَّارَة", translit="Sayyara — coche",
             teach="Coche en árabe es Sayyara. Literalmente: la que viaja.",
             cta="¡Dale like si te gustan los viajes por carretera!",
             themes=["desert road driving", "car road"]),
    35: dict(hook="Palabra del día: amigo", ar="صَدِيق", translit="Sadiq — amigo",
             teach="Un amigo de verdad es Sadiq. Viene de la palabra verdad.",
             cta="¡Mándaselo a tu amigo!",
             themes=["arabic coffee", "tea pouring glass"]),
    36: dict(hook="Palabra del día: madre", ar="أُمّ", translit="Umm — madre",
             teach="La palabra más importante de todas. Madre en árabe es Umm.",
             cta="¡Dale like si amas a tu mamá!",
             themes=["red rose garden", "cozy house interior"]),
    37: dict(hook="Palabra del día: padre", ar="أَب", translit="Ab — padre",
             teach="El padre, pilar de la familia. Padre en árabe es Ab.",
             cta="¡Suscríbete al canal!",
             themes=["old wooden door morocco", "compass vintage"]),
    38: dict(hook="Palabra del día: hermano", ar="أَخ", translit="Akh — hermano",
             teach="Hermano en árabe es Akh. Corta y fuerte.",
             cta="¡Mándaselo a tu hermano!",
             themes=["two camels desert", "bridge stone arch"]),
    39: dict(hook="Palabra del día: hermana", ar="أُخْت", translit="Ukht — hermana",
             teach="Hermana en árabe es Ukht. Tu mejor amiga de por vida.",
             cta="¡Mándaselo a tu hermana!",
             themes=["two roses garden", "butterflies pair"]),
    40: dict(hook="Palabra del día: manzana", ar="تُفَّاح", translit="Tuffah — manzana",
             teach="Una manzana al día. Manzana en árabe es Tuffah.",
             cta="¡Dale like si te gustan las manzanas!",
             themes=["red apples", "apple orchard"]),
    41: dict(hook="Palabra del día: té", ar="شَاي", translit="Shay — té",
             teach="Nada dice hospitalidad como un vaso de té. Té en árabe es Shay.",
             cta="¡Guárdalo antes de que se enfríe!",
             themes=["tea pouring glass", "tea"]),
    42: dict(hook="Palabra del día: cielo", ar="سَمَاء", translit="Samaa — cielo",
             teach="Mira hacia arriba. Cielo en árabe es Samaa.",
             cta="¡Suscríbete al canal!",
             themes=["clouds timelapse", "blue sky"]),
    43: dict(hook="Palabra del día: tierra", ar="أَرْض", translit="Ard — tierra",
             teach="Tierra, suelo, terreno. En árabe todo es Ard.",
             cta="¡Guarda esta palabra!",
             themes=["green landscape aerial", "earth nature"]),
    44: dict(hook="Palabra del día: vida", ar="حَيَاة", translit="Hayat — vida",
             teach="La vida es bella. Vida en árabe es Hayat.",
             cta="¡Suscríbete, queda mucho por aprender!",
             themes=["flower blooming timelapse", "nature life"]),
    45: dict(hook="Palabra del día: corazón", ar="قَلْب", translit="Qalb — corazón",
             teach="Habla desde el corazón. Corazón en árabe es Qalb.",
             cta="¡Dale like con el corazón!",
             themes=["red rose", "rose garden", "desert sunset"]),
    46: dict(hook="Palabra del día: luz", ar="نُور", translit="Nur — luz",
             teach="Una palabra bonita y también un nombre. Luz en árabe es Nur.",
             cta="¡Suscríbete para más luz!",
             themes=["ramadan lantern", "mosque lamp", "sheikh zayed mosque"]),
    47: dict(hook="Color del día: rojo", ar="أَحْمَر", translit="Ahmar — rojo",
             teach="Rojo en árabe es Ahmar. ¡Como el mar Rojo!",
             cta="¡Suscríbete y colecciona todos los colores!",
             themes=["morocco spices", "red rose", "sahara dunes"]),
    48: dict(hook="Color del día: verde", ar="أَخْضَر", translit="Akhdar — verde",
             teach="El verde es el color del oasis. En árabe es Akhdar.",
             cta="¡Dale like si amas la naturaleza!",
             themes=["green oasis", "palm grove", "oasis palm"]),
    49: dict(hook="Color del día: blanco", ar="أَبْيَض", translit="Abyad — blanco",
             teach="Blanco como el mármol de una mezquita. Blanco en árabe es Abyad.",
             cta="¡Suscríbete al canal!",
             themes=["white mosque", "sheikh zayed mosque", "white desert egypt"]),
    50: dict(hook="Palabra del día: mar", ar="بَحْر", translit="Bahr — mar",
             teach="Cierra los ojos y escucha las olas. Mar en árabe es Bahr.",
             cta="¡Dale like si amas el mar!",
             themes=["red sea", "sea waves", "beach sunset"]),
    51: dict(hook="Palabra del día: estrella", ar="نَجْمَة", translit="Najma — estrella",
             teach="Muchas estrellas todavía llevan nombres árabes. Estrella en árabe es Najma.",
             cta="¡Suscríbete, tú eres una estrella!",
             themes=["milky way desert", "starry night", "night sky"]),
    52: dict(hook="Palabra del día: rosa", ar="وَرْدَة", translit="Warda — rosa",
             teach="Una rosa, una flor. En árabe es Warda.",
             cta="¡Mándale esta flor a quien quieras!",
             themes=["rose garden", "jasmine flower", "flower field"]),
    53: dict(hook="Palabra del día: gato", ar="قِطَّة", translit="Qitta — gato",
             teach="Los gatos son queridos en todo el mundo árabe. Gato en árabe es Qitta.",
             cta="¡Dale like si tienes gato!",
             themes=["cat istanbul", "cat", "kitten"]),
    54: dict(hook="Azafrán es árabe", ar="الزَّعْفَرَان", translit="Az-zafaran — el azafrán",
             teach="La especia más cara del mundo tiene nombre árabe: Az-zafaran.",
             cta="¡Suscríbete para más palabras escondidas!",
             themes=["saffron", "morocco spices", "spice market stall"]),
    55: dict(hook="Palabra del día: pez", ar="سَمَك", translit="Samak — pez",
             teach="Pez en árabe es Samak. Útil en cualquier restaurante junto al mar.",
             cta="¡Guárdalo para tu próxima cena!",
             themes=["red sea fish", "coral reef", "fish"]),
    56: dict(hook="Palabra del día: camello", ar="جَمَل", translit="Jamal — camello",
             teach="El barco del desierto. Camello en árabe es Jamal.",
             cta="¡Suscríbete para más palabras del desierto!",
             themes=["camel desert", "desert dunes"]),
    57: dict(hook="Palabra del día: libro", ar="كِتَاب", translit="Kitab — libro",
             teach="El primer paso hacia cualquier idioma es un libro. Libro en árabe es Kitab.",
             cta="¡Suscríbete y sigue aprendiendo!",
             themes=["old books", "arabic manuscript", "library"]),
    # Уроки 58+: новые слова без повторов с 1–57; много испанских
    # арабизмов — это лучший крючок канала («ya hablas árabe»).
    58: dict(hook="Palabra del día: león", ar="أَسَد",
             translit="Asad — león",
             teach="El rey de la selva en árabe es Asad. Repite: Asad.",
             cta="¡Suscríbete y sé valiente como un león!",
             themes=["lion", "lion savanna", "lion mane"]),
    59: dict(hook="Palabra del día: halcón", ar="صَقْر",
             translit="Saqr — halcón",
             teach="El halcón es el ave nacional de los Emiratos. En árabe se dice Saqr.",
             cta="¡Suscríbete, mañana otra palabra!",
             themes=["falcon", "falcon flying", "peregrine falcon"]),
    60: dict(hook="Palabra del día: caballo", ar="حِصَان",
             translit="Hisan — caballo",
             teach="Los caballos árabes son famosos en todo el mundo. Caballo en árabe es Hisan.",
             cta="¡Dale like si te gustan los caballos!",
             themes=["arabian horse", "horse running", "white horse"]),
    61: dict(hook="Gacela viene del árabe", ar="غَزَال",
             translit="Ghazal — gacela",
             teach="La palabra gacela viene del árabe Ghazal. Ghazal, gacela.",
             cta="¡Suscríbete, hay muchas más palabras así!",
             themes=["gazelle", "gazelle desert", "dorcas gazelle"]),
    62: dict(hook="Palabra del día: espada", ar="سَيْف",
             translit="Sayf — espada",
             teach="Espada en árabe es Sayf. Repite: Sayf.",
             cta="¡Suscríbete para tu árabe diario!",
             themes=["damascus steel", "sword", "antique sword"]),
    63: dict(hook="Gibraltar es una palabra árabe", ar="جَبَل",
             translit="Jabal — montaña",
             teach="Gibraltar viene de Jabal Tariq: la montaña de Tariq. Montaña en árabe es Jabal.",
             cta="¡Comparte con quien no lo sabía!",
             themes=["rock of gibraltar", "mountain landscape", "mountain peak"]),
    64: dict(hook="Palabra del día: río", ar="نَهْر",
             translit="Nahr — río",
             teach="Río en árabe es Nahr. El Nilo es Nahr an-Nil.",
             cta="¡Suscríbete, mañana más!",
             themes=["river", "nile river", "river valley"]),
    65: dict(hook="Palabra del día: lluvia", ar="مَطَر",
             translit="Matar — lluvia",
             teach="Lluvia en árabe es Matar. Repite: Matar.",
             cta="¡Guárdalo para un día de lluvia!",
             themes=["rain", "rain drops", "rain window"]),
    66: dict(hook="Palabra del día: nieve", ar="ثَلْج",
             translit="Thalj — nieve",
             teach="¿Nieve en el desierto? Sí existe. Nieve en árabe es Thalj.",
             cta="¡Suscríbete y aprende una palabra al día!",
             themes=["snow", "snowy mountains", "snowflakes"]),
    67: dict(hook="Palabra del día: viento", ar="رِيح",
             translit="Rih — viento",
             teach="Viento en árabe es Rih. Repite: Rih.",
             cta="¡Suscríbete, el árabe es fácil!",
             themes=["wind dunes", "windy grass", "sand storm"]),
    68: dict(hook="Zoco viene del árabe", ar="سُوق",
             translit="Suq — mercado",
             teach="El zoco de Marruecos es el árabe Suq: mercado. Suq, zoco.",
             cta="¡Dale like si no lo sabías!",
             themes=["moroccan lanterns", "spices", "medina street"]),
    69: dict(hook="Alcalá viene del árabe", ar="قَلْعَة",
             translit="Qal'a — fortaleza",
             teach="Alcalá viene del árabe Qal'a: castillo, fortaleza. Repite: Qal'a.",
             cta="¡Comparte con alguien de Alcalá!",
             themes=["castle", "alcazaba", "fortress walls"]),
    70: dict(hook="Palabra del día: puente", ar="جِسْر",
             translit="Jisr — puente",
             teach="Puente en árabe es Jisr. Repite: Jisr.",
             cta="¡Suscríbete y cruza al árabe!",
             themes=["bridge", "stone bridge", "bridge river"]),
    71: dict(hook="Palabra del día: farol", ar="فَانُوس",
             translit="Fanus — farol",
             teach="El famoso farol de Ramadán se llama Fanus. Repite: Fanus.",
             cta="¡Guárdalo para Ramadán!",
             themes=["ramadan lantern", "moroccan lanterns", "lantern night"]),
    72: dict(hook="Palabra del día: anillo", ar="خَاتَم",
             translit="Khatam — anillo",
             teach="Anillo en árabe es Khatam. Repite: Khatam.",
             cta="¡Suscríbete, mañana más!",
             themes=["silver ring", "gold ring", "ring box"]),
    73: dict(hook="Palabra del día: perfume", ar="عِطْر",
             translit="Itr — perfume",
             teach="Los perfumes árabes son famosos. Perfume en árabe es Itr.",
             cta="¡Dale like si te encanta el perfume!",
             themes=["perfume bottle", "oud wood", "perfume oil"]),
    74: dict(hook="Jabón viene del árabe", ar="صَابُون",
             translit="Sabun — jabón",
             teach="Jabón y el árabe Sabun suenan casi igual. Sabun, jabón.",
             cta="¡Comparte con quien no lo sabía!",
             themes=["aleppo soap", "soap bars", "handmade soap"]),
    75: dict(hook="Palabra del día: sal", ar="مِلْح",
             translit="Milh — sal",
             teach="Sal en árabe es Milh. Repite: Milh.",
             cta="¡Suscríbete y dale sabor a tu árabe!",
             themes=["salt", "salt crystals", "salt flats"]),
    76: dict(hook="Limón viene del árabe", ar="لَيْمُون",
             translit="Laymun — limón",
             teach="Limón viene del árabe Laymun. Laymun, limón.",
             cta="¡Dale like si no lo sabías!",
             themes=["lemon", "lemon tree", "lemons"]),
    77: dict(hook="Palabra del día: granada", ar="رُمَّان",
             translit="Rumman — granada",
             teach="La fruta granada en árabe es Rumman. Repite: Rumman.",
             cta="¡Comparte con alguien de Granada!",
             themes=["pomegranate", "pomegranate seeds", "pomegranate tree"]),
    78: dict(hook="Aceituna viene del árabe", ar="الزَّيْتُونَة",
             translit="Az-zaytuna — la aceituna",
             teach="Aceituna viene del árabe Az-zaytuna. Az-zaytuna, aceituna.",
             cta="¡Suscríbete, hay más palabras escondidas!",
             themes=["olives", "olive tree", "green olives"]),
    79: dict(hook="Palabra del día: tren", ar="قِطَار",
             translit="Qitar — tren",
             teach="Tren en árabe es Qitar. Repite: Qitar.",
             cta="¡Guárdalo para tu próximo viaje!",
             themes=["train", "train station", "train tracks"]),
    80: dict(hook="Palabra del día: barco", ar="سَفِينَة",
             translit="Safina — barco",
             teach="Barco en árabe es Safina. Repite: Safina.",
             cta="¡Suscríbete y navega en árabe!",
             themes=["sailing ship", "ship sea", "dhow boat"]),
    81: dict(hook="Palabra del día: invitado", ar="ضَيْف",
             translit="Dayf — invitado",
             teach="En la cultura árabe el invitado es sagrado. Invitado en árabe es Dayf.",
             cta="¡Suscríbete, eres nuestro invitado!",
             themes=["arabic coffee", "tea set", "dates bowl"]),
    82: dict(hook="Palabra del día: vecino", ar="جَار",
             translit="Jar — vecino",
             teach="Vecino en árabe es Jar. Repite: Jar.",
             cta="¡Etiqueta a tu vecino!",
             themes=["neighborhood street", "houses street", "village houses"]),
    83: dict(hook="Palabra del día: feliz", ar="سَعِيد",
             translit="Sa'id — feliz",
             teach="Feliz en árabe es Sa'id. ¡Que tengas un día Sa'id!",
             cta="¡Suscríbete y sé feliz!",
             themes=["sunflower field", "sunrise", "flower garden"]),
    84: dict(hook="Palabra del día: invierno", ar="شِتَاء",
             translit="Shitaa — invierno",
             teach="Invierno en árabe es Shitaa. Repite: Shitaa.",
             cta="¡Guárdalo para el invierno!",
             themes=["winter landscape", "snowy forest", "winter trees"]),
    85: dict(hook="Palabra del día: mariposa", ar="فَرَاشَة",
             translit="Farasha — mariposa",
             teach="Mariposa en árabe es Farasha. Repite: Farasha.",
             cta="¡Dale like si te gustan las mariposas!",
             themes=["butterfly", "butterfly flower", "monarch butterfly"]),
    86: dict(hook="Palabra del día: abeja", ar="نَحْلَة",
             translit="Nahla — abeja",
             teach="Abeja en árabe es Nahla. Hay una sura del Corán con ese nombre: Nahla.",
             cta="¡Suscríbete y trabaja como una abeja!",
             themes=["honey bee", "bee flower", "beehive"]),
    87: dict(hook="Palabra del día: zorro", ar="ثَعْلَب",
             translit="Tha'lab — zorro",
             teach="El astuto zorro en árabe es Tha'lab. Repite: Tha'lab.",
             cta="¡Suscríbete, mañana más!",
             themes=["fennec fox", "red fox", "fox"]),
    88: dict(hook="Aldea viene del árabe", ar="الضَّيْعَة",
             translit="Ad-day'a — la aldea",
             teach="Aldea viene del árabe Ad-day'a: el pueblo. Ad-day'a, aldea.",
             cta="¡Comparte si vives en una aldea!",
             themes=["mountain village", "white village", "village houses"]),
    89: dict(hook="Alcalde viene del árabe", ar="الْقَاضِي",
             translit="Al-qadi — el juez",
             teach="Alcalde viene del árabe Al-qadi, que significa el juez. Al-qadi, alcalde.",
             cta="¡Dale like si no lo sabías!",
             themes=["town hall", "old courthouse", "spanish town square"]),
    90: dict(hook="Ajedrez viene del árabe", ar="الشِّطْرَنْج",
             translit="Ash-shitranj — el ajedrez",
             teach="Ajedrez viene del árabe Ash-shitranj. Repite: Ash-shitranj.",
             cta="¡Etiqueta a tu rival de ajedrez!",
             themes=["chess", "chess board", "chess pieces"]),
    91: dict(hook="Azulejo viene del árabe", ar="الزُّلَيْج",
             translit="Az-zulayj — el azulejo",
             teach="Azulejo viene del árabe Az-zulayj, los mosaicos de Marruecos. Az-zulayj, azulejo.",
             cta="¡Guárdalo si te gustan los azulejos!",
             themes=["zellige", "moroccan tiles", "alhambra tiles"]),
    92: dict(hook="Algodón viene del árabe", ar="الْقُطْن",
             translit="Al-qutn — el algodón",
             teach="Algodón viene del árabe Al-qutn. Al-qutn, algodón.",
             cta="¡Suscríbete, hay más palabras así!",
             themes=["cotton", "cotton field", "cotton flower"]),
    93: dict(hook="Almacén viene del árabe", ar="الْمَخْزَن",
             translit="Al-makhzan — el almacén",
             teach="Almacén viene del árabe Al-makhzan. Al-makhzan, almacén.",
             cta="¡Dale like si no lo sabías!",
             themes=["warehouse", "old storehouse", "storage shelves"]),
    94: dict(hook="Berenjena viene del árabe", ar="بَاذِنْجَان",
             translit="Badhinjan — berenjena",
             teach="Berenjena viene del árabe Badhinjan. Badhinjan, berenjena.",
             cta="¡Comparte con quien ama la berenjena!",
             themes=["eggplant", "aubergine", "eggplants"]),
    95: dict(hook="Jazmín viene del árabe", ar="يَاسَمِين",
             translit="Yasamin — jazmín",
             teach="Jazmín viene del árabe Yasamin. Yasamin, jazmín.",
             cta="¡Suscríbete y aprende algo bonito!",
             themes=["jasmine flower", "jasmine", "white flowers"]),
    96: dict(hook="Taza viene del árabe", ar="طَاسَة",
             translit="Tasa — taza",
             teach="Taza viene del árabe Tasa. Tasa, taza. ¿Casi igual, verdad?",
             cta="¡Dale like con tu taza de café!",
             themes=["tea cup", "coffee cup", "brass bowl"]),
    97: dict(hook="Alfiler viene del árabe", ar="الْخِلَال",
             translit="Al-khilal — el alfiler",
             teach="Alfiler viene del árabe Al-khilal. Al-khilal, alfiler.",
             cta="¡Comparte con quien no lo sabía!",
             themes=["sewing pins", "pin cushion", "sewing kit"]),
    98: dict(hook="Hasta viene del árabe", ar="حَتَّى",
             translit="Hatta — hasta",
             teach="La palabra hasta viene del árabe Hatta. Hatta, hasta.",
             cta="¡Suscríbete, hasta mañana!",
             themes=["road horizon", "desert road", "sunset horizon"]),
    99: dict(hook="Alquiler viene del árabe", ar="الْكِرَاء",
             translit="Al-kira — el alquiler",
             teach="Alquiler viene del árabe Al-kira. Al-kira, alquiler.",
             cta="¡Dale like si pagas alquiler!",
             themes=["apartment building", "house keys", "old town houses"]),
    100: dict(hook="Alcachofa viene del árabe", ar="الْخَرْشُوفَة",
             translit="Al-kharshufa — la alcachofa",
             teach="Alcachofa viene del árabe Al-kharshufa. Al-kharshufa, alcachofa.",
             cta="¡Suscríbete, hay más palabras escondidas!",
             themes=["artichoke", "artichokes", "artichoke flower"]),
    101: dict(hook="Albaricoque viene del árabe", ar="الْبَرْقُوق",
             translit="Al-barquq — el albaricoque",
             teach="Albaricoque viene del árabe Al-barquq. Al-barquq, albaricoque.",
             cta="¡Dale like si te gustan los albaricoques!",
             themes=["apricot", "apricots", "apricot tree"]),
    102: dict(hook="Alberca viene del árabe", ar="الْبِرْكَة",
             translit="Al-birka — la alberca",
             teach="Alberca viene del árabe Al-birka: el estanque. Al-birka, alberca.",
             cta="¡Comparte con quien no lo sabía!",
             themes=["alhambra pool", "garden pool", "reflecting pool"]),
    103: dict(hook="Noria viene del árabe", ar="النَّاعُورَة",
             translit="An-na'ura — la noria",
             teach="Noria viene del árabe An-na'ura, la rueda de agua. An-na'ura, noria.",
             cta="¡Dale like si no lo sabías!",
             themes=["water wheel", "noria hama", "old water wheel"]),
    104: dict(hook="Acequia viene del árabe", ar="السَّاقِيَة",
             translit="As-saqiya — la acequia",
             teach="Acequia viene del árabe As-saqiya: el canal de riego. As-saqiya, acequia.",
             cta="¡Suscríbete, hay muchas más!",
             themes=["irrigation canal", "water channel", "garden canal"]),
    105: dict(hook="Jirafa viene del árabe", ar="زَرَافَة",
             translit="Zarafa — jirafa",
             teach="Jirafa viene del árabe Zarafa. Zarafa, jirafa.",
             cta="¡Dale like si te gustan las jirafas!",
             themes=["giraffe", "giraffe savanna", "giraffes"]),
    106: dict(hook="Café viene del árabe", ar="قَهْوَة",
             translit="Qahwa — café",
             teach="Café viene del árabe Qahwa. Qahwa, café.",
             cta="¡Comenta si tomas café ahora mismo!",
             themes=["arabic coffee", "coffee beans", "coffee pot"]),
    107: dict(hook="Tarifa viene del árabe", ar="تَعْرِيفَة",
             translit="Ta'rifa — tarifa",
             teach="Tarifa viene del árabe Ta'rifa: lista de precios. Ta'rifa, tarifa.",
             cta="¡Comparte con alguien de Tarifa!",
             themes=["tarifa beach", "price tags", "old harbor"]),
    108: dict(hook="Almirante viene del árabe", ar="أَمِير",
             translit="Amir — príncipe",
             teach="Almirante viene del árabe Amir: el que manda. Amir, almirante.",
             cta="¡Dale like si no lo sabías!",
             themes=["old sailing ship", "lighthouse", "ship sea"]),
    109: dict(hook="Alhaja viene del árabe", ar="الْحَاجَة",
             translit="Al-haja — la alhaja",
             teach="Alhaja viene del árabe Al-haja: algo valioso. Al-haja, alhaja.",
             cta="¡Suscríbete, eres una alhaja!",
             themes=["jewellery", "gold necklace", "gemstones"]),
    110: dict(hook="Color del día: azul", ar="أَزْرَق",
             translit="Azraq — azul",
             teach="Azul en árabe es Azraq. Como el mar: Azraq.",
             cta="¡Dale like si tu color es el azul!",
             themes=["blue sea", "chefchaouen", "blue tiles"]),
    111: dict(hook="Color del día: negro", ar="أَسْوَد",
             translit="Aswad — negro",
             teach="Negro en árabe es Aswad. Repite: Aswad.",
             cta="¡Suscríbete, mañana otro color!",
             themes=["black sand", "black stone", "night sky"]),
    112: dict(hook="Color del día: amarillo", ar="أَصْفَر",
             translit="Asfar — amarillo",
             teach="Amarillo en árabe es Asfar. Como el sol del desierto: Asfar.",
             cta="¡Dale like si te gusta el amarillo!",
             themes=["yellow flowers", "sunflower", "desert sand"]),
}

INTRO_PHRASES = [
    "Así suena en árabe",
    "Escucha la pronunciación real en árabe",
    "Así se dice en árabe",
    "Escucha con atención cómo suena en árabe",
]
REPEAT_PHRASES = [
    "Una vez más",
    "Otra vez, despacio",
    "De nuevo, para que se te quede",
    "Escúchalo otra vez",
]
MEANING_LEADS = [
    "Recuerda",
    "No lo olvides",
    "Apúntalo",
    "Que no se te olvide",
]
ASK_PHRASES = [
    "Ahora dilo en voz alta",
    "Te toca, dilo en voz alta",
    "Inténtalo tú",
    "Repite conmigo",
]
OUTRO_PHRASES = [
    "¡Muy bien!",
    "¡Perfecto, lo tienes!",
    "¡Genial, lo estás haciendo muy bien!",
    "¡Bravo, sigue así!",
]

CTA_TEXT = "Aprende árabe, una palabra al día. ¡Suscríbete!"

GROUPS = {
    "prestamos": ([2, 4, 7, 10, 13, 16, 19, 22, 25, 54],
                  ["palabras árabes en español", "origen de las palabras",
                   "etimología", "arabismos", "curiosidades del idioma"],
                  "#etimologia #arabismos #curiosidadesdelidioma"),
    "saludos": ([1, 5, 18, 20, 21, 23, 24],
                ["saludos en árabe", "como saludar en árabe",
                 "frases en árabe", "hablar árabe"],
                "#saludosenarabe #frasesenarabe #hablararabe"),
    "frases": ([6, 8, 9, 11, 12, 14, 15, 17, 26, 27],
               ["frases en árabe", "árabe para viajar",
                "conversación en árabe", "árabe útil"],
               "#frasesenarabe #arabeparaviajar #hablararabe"),
    "colores": ([47, 48, 49],
                ["colores en árabe", "vocabulario árabe"],
                "#coloresenarabe #vocabularioarabe"),
    "familia": ([36, 37, 38, 39],
                ["familia en árabe", "vocabulario árabe"],
                "#familiaenarabe #vocabularioarabe"),
}
BASE_TAGS = ["aprender árabe", "árabe", "árabe para principiantes",
             "palabras en árabe", "clase de árabe", "shorts"]
BASE_HASHTAGS = "#aprenderarabe #arabe #arabeparaprincipiantes"

LANG = core.Lang(
    code="es", channel="Árabe Fácil",
    voice="es-MX-DaliaNeural", rate="-5%",
    lessons=LESSONS,
    intro=INTRO_PHRASES, repeat=REPEAT_PHRASES,
    meaning_lead=MEANING_LEADS, means="{word} significa {meaning}.",
    ask=ASK_PHRASES, outro=OUTRO_PHRASES,
    cta_text=CTA_TEXT,
    base_tags=BASE_TAGS, base_hashtags=BASE_HASHTAGS,
    groups=GROUPS,
    default_group=(["vocabulario árabe", "palabra del día",
                    "árabe para principiantes"],
                   "#vocabularioarabe #palabradeldia"),
    meaning_tag="{meaning} en árabe", word_tag="palabra árabe {word}",
)

OUT_DIR = LANG.out_dir
split_translit = core.split_translit


def tags_for(n):
    return core.tags_for(LANG, n)


def hashtags_for(n):
    return core.hashtags_for(LANG, n)


def build_short(n):
    return core.build_short(LANG, n)


if __name__ == "__main__":
    core.cli(LANG)
